apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./helm-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
