apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-addons
  namespace: kube-infra
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  path: ./infrastructure-addons/io
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
