apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-exporter
  namespace: starboard-operator
spec:
  chart:
    spec:
      # renovate: registryUrl=https://giantswarm.github.io/giantswarm-catalog
      chart: starboard-exporter
      version: "0.6.2"
  values:
    exporter:
      vulnerabilityReports:
        targetLabels:
          - image_namespace
          - image_repository
          - image_tag
          - vulnerability_id
    monitoring:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack

