apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-exporter
  namespace: starboard-operator
spec:
  chart:
    spec:
      # renovate: registryUrl=https://giantswarm.github.io/giantswarm-catalog
      chart: starboard-exporter
      version: "0.5.1"
