apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: kube-infra
spec:
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: kube-infra
  interval: 10m0s
  dependsOn:
    - name: kube-prometheus-stack
  values:
    serviceMonitor:
      enabled: true
      namespace: kube-infra
      interval: 10s
      scrapeTimeout: 10s
      jobLabel: fluentbit
      selector:
        prometheus: default
        release: kube-prometheus-stack
      ## metric relabel configs to apply to samples before ingestion.
      ##
      metricRelabelings:
        - sourceLabels: [__meta_kubernetes_service_label_cluster]
          targetLabel: cluster
          regex: (.*)
          replacement: ${1}
          action: replace
      ## relabel configs to apply to samples after ingestion.
      ##
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
    prometheusRule:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      rules:
      - alert: NoOutputBytesProcessed
        expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
        annotations:
          message: |
            Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
            bytes for at least 15 minutes.
          summary: No Output Bytes Processed
        for: 15m
        labels:
          severity: critical
    dashboards:
      enabled: true
    tolerations: 
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    config:
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Merge_Log_Trim On
            Labels Off
            Annotations Off
            K8S-Logging.Parser Off
            K8S-Logging.Exclude Off

        [FILTER]
            Name nest
            Match kube.*
            Operation lift
            Nested_under kubernetes
            Add_prefix   kubernetes_

        [FILTER]
            Name modify
            Match kube.*
            Rename log msg
            Rename kubernetes_pod_name pod
            Rename kubernetes_namespace_name namespace
            Rename kubernetes_container_name container
            Remove kubernetes_container_image
            Remove kubernetes_docker_id
            Remove kubernetes_pod_id
            Remove kubernetes_host
            Remove time
            Remove kubernetes_container_hash
            Add job 
            Add cluster io
      outputs: |
        [OUTPUT]
            Name loki
            Match kube.*
            host loki
            port 3100
            tenant_id ""
            labels type=k8s stream=$stream
            auto_kubernetes_labels on
            line_format json