apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-operator
spec:
  chart:
    spec:
      # renovate: registryUrl=https://aquasecurity.github.io/helm-charts
      chart: starboard-operator
      version: "0.10.6"
