apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: kube-infra
spec:
  chart:
    spec:
      # renovate: registryUrl=https://fluent.github.io/helm-charts
      chart: fluent-bit
      version: "0.19.23"
  values:
    podLabels:
      - name: cluster-name
        value: io