---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: kube-infra
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repositories
  path: ./infrastructure/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: cert-manager
        namespace: kube-infra
      spec:
        chart:
          spec:
            # renovate: registryUrl=https://charts.jetstack.io/
            chart: cert-manager
            version: "1.4.0"
        values:
          volumeMounts:
            - mountPath: /.aws
              name: credentials
              readOnly: true
          volumes:
            - name: credentials
              secret:
                secretName: cert-manager-route53-credentials     
    target:
      kind: HelmRelease
      name: cert-manager
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
    - apiVersion: v1
      kind: Service
      name: cert-manager-webhook
      namespace: cert-managero
