apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
patches:
  - target:
      kind: Certificate
      name: selfsigned-ca
    patch: |-
      spec:
        commonName: io-selfsigned-ca