apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
patchesJson6902:
  - target:
      version: v1
      group: cert-manager.io
      kind: Certificate
      name: selfsigned-ca
    patch: |-
      - op: replace
        path: /spec/commonName
        value: io-selfsigned-ca
    