apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
patchesStrategicMerge:
  - letsencrypt-production-wildcard.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - selfsigned-clusterissuer.yaml