apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-exporter
  namespace: starboard-operator
spec:
  chart:
    spec:
      chart: starboard-exporter
      sourceRef:
        kind: HelmRepository
        name: giantswarm
        namespace: flux-system
  interval: 10m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
  dependsOn:
    - name: starboard-operator
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: grafana-starboard
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kube-infra"