---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: csi-driver
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./deploy/kubernetes/hcloud-csi.yml
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-driver
