apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  namespace: kube-infra
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - flux-system
  podMetricsEndpoints:
  - port: http-prom
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - helm-controller
      - source-controller
      - kustomize-controller
      - notification-controller
      - image-automation-controller
      - image-reflector-controller