apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-infra
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: "4.3.0"
  values:
    controller:
      extraArgs:
        default-ssl-certificate: default/letsencrypt-production-wildcard
      replicaCount: 3
      minAvailable: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      autoscaling:
        minReplicas: 3
    defaultBackend:
      extraEnvs:
        - name: ERROR_FILES_PATH
          value: ./themes/ghost