apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-infra
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      strategy: uninstall
  values:
    crd:
      create: true
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    sources:
      - service
      - ingress
    interval: "1m"
    registry: "txt"
    txtOwnerId: "external-dns"
    policy: sync
