apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-infra
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      strategy: uninstall
  values:
    grafana:
      persistence:
        enabled: true
      imageRenderer:
        enabled: true
        env:
          BROWSER_TZ: "Europe/Berlin"
          ENABLE_METRICS: true
        networkPolicy:
          limitIngress: false
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
      sidecar:
        dashboards:
          searchNamespace: All
          folderAnnotation: k8s-sidecar-target-directory
          folder: /tmp/dashboards
          provider:
            foldersFromFilesStructure: true
          annotations: 
            k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
