apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-infra
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-infra
  interval: 10m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      imageRenderer:
        enabled: false
        env:
          BROWSER_TZ: "Europe/Berlin"
          HTTP_HOST: 0.0.0.0
          ENABLE_METRICS: true
        networkPolicy:
          limitIngress: false