apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-infra
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-infra
  interval: 10m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retires: 10
  values:
    grafana:
      persistence:
        enabled: true
        size: 1Gi
      imageRenderer:
        enabled: true
        env:
          BROWSER_TZ: "Europe/Berlin"
          ENABLE_METRICS: true
        networkPolicy:
          limitIngress: false
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
      sidecar:
        dashboards:
          folderAnnotation: k8s-sidecar-target-directory