---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1m0s
  values:
    #19
    fullnameOverride: "prometheus"
    #509
    grafana:
      enabled: false
    #1105
    nodeExporter:
      enabled: true
    #1408
    prometheus:
      #2008
      additionalServiceMonitors:
        - name: "metrics-server"
          selector:
            matchLabels:
              app: metrics-server
          namespaceSelector:
            matchNames:
              - kube-system
          endpoints:
            - path: /metrics
              port: metrics
        - name: "flux"
          selector:
            matchLabels:
              app: node-exporter
          namespaceSelector:
            matchNames:
              - flux-system
          endpoints:
            - path: /metrics
              port: metrics
        - name: "grafana-metrics"
          selector:
            matchLabels:
              app: grafana
          namespaceSelector:
            matchNames:
              - monitoring
          endpoints:
            - path: /metrics
              port: service
              honorLabels: true
              interval: 1m
              scrapeTimeout: 30s
        - name: "nginx-ingress-ingress-nginx-controller-metrics"
          selector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
          namespaceSelector:
            matchNames:
              - nginx-ingress
          endpoints:
            - path: /metrics
              port: metrics
      additionalPodMonitors:
        - name: "flux"
          namespaceSelector:
            matchNames: flux-system
          endpoints:
            - path: /metrics
              port: http-prom
