apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production-wildcard
  namespace: kube-infra
spec:
  secretName: letsencrypt-production-wildcard
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
