apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: hostmaster+production@kube.uno
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            region: eu-central-1
      - http01:
          ingress:
            serviceType: ClusterIP
            class: nginx
        selector:
          matchLabels:
            use-http01-solver: "true"
