apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-loki
  labels:
    grafana_datasource: "1"
    namespace: kube-infra
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki:3100